### ISSUE TITLE
Error after downloading version 1.0.1

### ISSUE THREAD

**Issue by xacobofg** [pluginsGLPI/oauthimap#4]
When I download the plugin from the marketplace I get the error `Uncaught Exception Laminas\I18n\Exception\ParseException: Unknown or invalid parser rule: nplurals=INTEGER; plural=EXPRESSION; in /var/www/html/vendor/laminas/laminas-i18n/src/Translator/Plural/Rule.php at line 192` blocking the plugin page
If I select French as language the error does not appear but the plugin appears without name
![imagen](https://user-images.githubusercontent.com/39123808/96119952-068f6c00-0eee-11eb-91fc-2d50ccb48b9b.png)

**Comment by btry** [comment]
Hi

Which is your langage in your GLPI when this error occurs?

**Comment by xacobofg** [comment]
Hi.
I think @cedric-anne solved it in the commit https://github.com/pluginsGLPI/oauthimap/commit/5726935b3448576783ea81ec3f0e5751bc23231f

**Comment by btry** [comment]
I agree. Upgrade and see if the problem persists.

**Comment by cedric-anne** [comment]
Hi,

Indeed, this has been fixed in 1.0.2.

Regards
