### ISSUE TITLE
Office 365 Support

### ISSUE THREAD

**Issue by ZB92** [pluginsGLPI/oauthimap#5]
Hello,

Thank you so much for getting this plugin out there! This i am sure has helped a ton of people!

Will this plugin support Office 365 in the future? That is what my organization is using, but they will not allow old versions of IMAP to be turned on, so we are having issues with the mail receiver. 

Just wanted to know, sorry if this was the wrong place to ask!

Thanks!

-Z

**Comment by cedric-anne** [comment]
Hi,

Office 365 is currently supported. It requires to create a Azure AD oauth application.
Plugin documentation: https://glpi-plugins.readthedocs.io/en/latest/oauthimap/index.html
Microsoft documentation: https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

Regards
