### ISSUE TITLE
Unable to save authorization code

### ISSUE THREAD

**Issue by aprigio311** [pluginsGLPI/oauthimap#68]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

GLPI 10.0.15

### Plugin version

1.4.3

### Bug description

**I can't use the plugin, in the moment of authentication... only print message "Unable to save authorization code".**

**And the logs printed this:**

Timestamp: 2024-11-18 14:27:36Z in /var/www/html/glpi/plugins/oauthimap/inc/authorization.class.php at line 423
  Backtrace :
  plugins/oauthimap/inc/authorization.class.php:423  trigger_error()
  ...s/oauthimap/front/authorization.callback.php:77 PluginOauthimapAuthorization->createFromCode()
  public/index.php:82                                require()
  
[2024-11-18 14:31:45] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to get user email in /var/www/html/glpi/plugins/oauthimap/inc/authorization.class.php at line 434
  Backtrace :
  plugins/oauthimap/inc/authorization.class.php:434  trigger_error()
  ...s/oauthimap/front/authorization.callback.php:77 PluginOauthimapAuthorization->createFromCode()
  public/index.php:82                                require()
  
[2024-11-18 14:35:58] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to get user email in /var/www/html/glpi/plugins/oauthimap/inc/authorization.class.php at line 434
  Backtrace :
  plugins/oauthimap/inc/authorization.class.php:434  trigger_error()
  ...s/oauthimap/front/authorization.callback.php:77 PluginOauthimapAuthorization->createFromCode()
  public/index.php:82

### Relevant log output

```shell
Timestamp: 2024-11-18 14:27:36Z in /var/www/html/glpi/plugins/oauthimap/inc/authorization.class.php at line 423
  Backtrace :
  plugins/oauthimap/inc/authorization.class.php:423  trigger_error()
  ...s/oauthimap/front/authorization.callback.php:77 PluginOauthimapAuthorization->createFromCode()
  public/index.php:82                                require()
  
[2024-11-18 14:31:45] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to get user email in /var/www/html/glpi/plugins/oauthimap/inc/authorization.class.php at line 434
  Backtrace :
  plugins/oauthimap/inc/authorization.class.php:434  trigger_error()
  ...s/oauthimap/front/authorization.callback.php:77 PluginOauthimapAuthorization->createFromCode()
  public/index.php:82                                require()
  
[2024-11-18 14:35:58] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to get user email in /var/www/html/glpi/plugins/oauthimap/inc/authorization.class.php at line 434
  Backtrace :
  plugins/oauthimap/inc/authorization.class.php:434  trigger_error()
  ...s/oauthimap/front/authorization.callback.php:77 PluginOauthimapAuthorization->createFromCode()
  public/index.php:82
```

### Your GLPI setup information

GLPI 10.0.15 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:pt_BR

**Comment by stonebuzz** [comment]
Hi @aprigio311 

To address the error related to the expired token, I suggest revoking the current authorization on Azure and initiating a new authorization request through the plugin. Please follow the steps below:

## Revoking Authorization on Azure
1. Log in to the **Azure portal** as an administrator.
2. Navigate to **Azure Active Directory > App Registrations**.
3. Locate the application used by the plugin.
4. Remove the granted authorization by selecting **Revoke admin consent**.

## Initiating a New Authorization Request via the Plugin
1. Start the **OAuth authorization process** to generate a new token.
3. Follow the steps to grant the necessary permissions.

Best regards

**Comment by stonebuzz** [comment]
Hi @aprigio311 

Okay, the token is now being retrieved correctly. 

However, it seems that the account used for authorization is not associated with an email address. Could you please confirm or refute this?

**Comment by aprigio311** [comment]
**I confirmed account utilized, but now GLPI sends me log erros:**

2024-11-22 11:37:58 
Internal #1: Launch olaticket
2024-11-22 11:38:05 
Internal #1: Launch mailgate
2024-11-22 11:38:07 
An error occurred trying to connect to the collector.<br/>cannot login, user or password wrong
2024-11-22 11:43:58 
Interno #1: Executar graph

**User and password are correct.**

[2024-11-22 11:44:40] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot login, user or password wrong in .../plugins/oauthimap/inc/imap/imapoauthstorage.class.php at line 76

**Comment by stonebuzz** [comment]
Hi 
can you post the whole trace here?

**Comment by stonebuzz** [comment]
Check the configuration of your mail collector to see if the folder for transferring OK / KO mails exists.

**Comment by aprigio311** [comment]
Can you help me to find this path?

**Comment by stonebuzz** [comment]
![image](https://github.com/user-attachments/assets/741a7830-8eb6-4199-aa5a-87c109779708)

**Comment by aprigio311** [comment]
Okay, I verified this option and was empty..
So, I created the folder GLPI in e-mail account and applied this value, but I continue with the same errors...

**Comment by stonebuzz** [comment]
and for this

![image](https://github.com/user-attachments/assets/65e3d3c5-3683-4146-8bc1-6c3675cc0881)

do you use the default value “INBOX”?

**Comment by aprigio311** [comment]
Yes, I tried with "INBOX", "Inbox" and empty, and received the same errors log

**Comment by stonebuzz** [comment]
the INBOX folder exists in the account used to connect mails?

**Comment by aprigio311** [comment]
Yes, the folder INBOX exists in the account used to connect mails...
![WhatsApp Image 2024-11-22 at 11 31 59](https://github.com/user-attachments/assets/8d433d28-1237-422f-a881-4205bcc5787d)

**Comment by stonebuzz** [comment]
What is your provider? Office 365?

**Comment by aprigio311** [comment]
yes...
server: outlook.office365.com

**Comment by stonebuzz** [comment]
Can you try this

On your Tenant, in “APIs used by my organization”, search for “Office 365 Exchange” and select “Office 365 exchange online” then “delegated authorization”.
In the menu below, select “mail” and activate the authorizations below, then click on “add authorization”.

- Mail.Read
- Mail.Read.All
- Mail.Read.Shared
- Mail.ReadBasic
- Mail.ReadWrite

**Comment by aprigio311** [comment]
Now It's ok, the license on Exchange was wrong, thank you @stonebuzz !
